services:
  postgres:
    image: postgres:16
    container_name: agentflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agentflow_clients_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
